### ISSUE TITLE
Add Unfocus feature to "Focus" workflow

### ISSUE THREAD

**Issue by skibitsky** [nikitavoloboev/small-workflows#15]
Sometimes it is necessary to disable Focus which is not possible to achieve from the workflow. 
I propose to add `unfocus` feature that will execute `open focus://unfocus`

**Comment by nikivdev** [comment]
Sure, you can add it and send PR.

I don't use the Focus workflow myself. My focus [works on a schedule](https://wiki.nikitavoloboev.xyz/focusing) and I call this macro when I need few minutes of Unfocus time:

![2019-06-28 at 10 44](https://user-images.githubusercontent.com/6391776/60333742-b6effe80-9991-11e9-85d1-85fc5fe44b27.png)

**Comment by skibitsky** [comment]
Done in #16 
Unfortunately, scheduling doesn't work for me. Every day is different 😸
